# Generated by Django 3.2.12 on 2023-05-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
