# Generated by Django 3.2.12 on 2023-05-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20230514_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('ذخیره', 'ذخیره'), ('انتشار', 'ذخیره و انتشار')], default='ذخیره', max_length=7, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='article',
            name='subheading',
            field=models.CharField(default='', max_length=100, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='cover_images/'),
        ),
    ]
